---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: goreleaser
on:
  push:
    tags:
      - v*
    branches:
      - new-rebase
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io for CI
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Login to Quay.io
      #  uses: docker/login-action@v2
      #  with:
      #    registry: quay.io
      #    username: ${{ secrets.DOCKER_USER }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run GoReleaser for snapshot
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --clean
        env:
          GORELEASER_CURRENT_TAG: "v0.14.0-beta.3"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish latest snapshot image
        if: "!startsWith(github.ref, 'refs/tags/')"
        #env:
        #  DOCKER_USER: ${{ secrets.DOCKER_USER }}
        #  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          #docker push ghcr.io/syself/hetzner-cloud-controller-manager:v0.14.0-beta.3 # TODO change "v0.14.0-betaX" to "latest"
          for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep hetzner-cloud-controller-manager); do
              echo pushing "$image"
              docker push $image
          done
      - name: Run GoReleaser for tag
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          # https://github.com/goreleaser/goreleaser/blob/3345f8c9c5b287198a29d3db228388148b788c5e/www/docs/customization/builds.md?plain=1#L416-L418
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHART_REPO_REMOTE: "https://${{ secrets.HCLOUD_BOT_TOKEN }}@github.com/hetznercloud/helm-charts"

      - name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json
